/**
 * Generate FILE-MAP.md — the directory index agents jump to instead of crawling.
 *
 * Ported from the sibling f1-race-tracker repo's `scripts/gen_file_map.py`.
 * This repo is TypeScript-only (Vite app + a small serverless `api/`), so the
 * Go/Python description readers are dropped and only the TSDoc
 * `@packageDocumentation` reader remains. Written in Node/TypeScript rather
 * than Python because the repo has no Python anywhere and already runs its
 * other scripts (`build-dataset.ts`, `check-docs.ts`, `meta-coverage.ts`) via
 * `tsx` — adding a Python interpreter as a second toolchain for one script
 * would be pure overhead.
 *
 * Descriptions are pulled from what the code already declares (a TSDoc
 * `@packageDocumentation` block), so there is nothing extra to keep in sync:
 * change the doc comment, regenerate, done. Directories with no such
 * declaration render an empty Purpose, which makes the undocumented corners
 * visible rather than inventing prose for them.
 *
 *   npx tsx scripts/gen-file-map.ts            # rewrite FILE-MAP.md
 *   npx tsx scripts/gen-file-map.ts --check    # exit 1 if FILE-MAP.md is stale (CI)
 */
import * as fs from 'fs';
import * as path from 'path';

const ROOT = process.cwd();
const OUT = path.join(ROOT, 'FILE-MAP.md');

// Trees worth mapping, in reading order. Everything else (node_modules,
// dist, coverage, .vercel, build output, caches) is deliberately absent —
// the map is for source.
const ROOTS = ['src', 'api', 'scripts'];
const SOURCE_SUFFIXES = new Set(['.ts', '.tsx']);
const SKIP_DIR_PARTS = new Set(['node_modules', 'dist', 'coverage', '.vercel']);

interface Row {
  dir: string;
  count: number;
  desc: string;
}

function firstSentence(text: string, capitalize = true): string {
  const collapsed = text.split(/\s+/).filter(Boolean).join(' ');
  if (!collapsed) return '';
  // Keep it to one sentence so the table stays scannable.
  const cut = collapsed.split(/(?<=[.!?])\s/)[0];
  return capitalize ? cut.charAt(0).toUpperCase() + cut.slice(1) : cut;
}

/** First `/** ... @packageDocumentation *\/` block in a .ts/.tsx file. */
function tsDoc(dir: string): string {
  const files = fs
    .readdirSync(dir)
    .filter((f) => {
      const ext = path.extname(f);
      return SOURCE_SUFFIXES.has(ext) && !f.includes('.test.');
    })
    .sort();
  for (const f of files) {
    const src = fs.readFileSync(path.join(dir, f), 'utf-8');
    const m = /^\s*\/\*\*(.*?)\*\//s.exec(src);
    if (m && m[1].includes('@packageDocumentation')) {
      const body = m[1].replace('@packageDocumentation', '');
      const lines = body
        .split('\n')
        .map((ln) => ln.trim().replace(/^\*/, '').trim());
      const text = lines.filter(Boolean).join(' ');
      if (text) return firstSentence(text);
    }
  }
  return '';
}

function collectDirs(): Row[] {
  const rows: Row[] = [];
  for (const r of ROOTS) {
    const base = path.join(ROOT, r);
    if (!fs.existsSync(base) || !fs.statSync(base).isDirectory()) continue;
    const dirs = [base, ...walkDirs(base)].sort();
    for (const d of dirs) {
      const relParts = path.relative(ROOT, d).split(path.sep);
      if (relParts.some((p) => SKIP_DIR_PARTS.has(p))) continue;
      const files = fs.readdirSync(d, { withFileTypes: true });
      const n = files.filter(
        (f) => f.isFile() && SOURCE_SUFFIXES.has(path.extname(f.name)),
      ).length;
      if (n > 0) {
        rows.push({
          dir: path.relative(ROOT, d).split(path.sep).join('/'),
          count: n,
          desc: tsDoc(d),
        });
      }
    }
  }
  return rows;
}

function walkDirs(base: string): string[] {
  const out: string[] = [];
  for (const entry of fs.readdirSync(base, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    if (SKIP_DIR_PARTS.has(entry.name)) continue;
    const full = path.join(base, entry.name);
    out.push(full, ...walkDirs(full));
  }
  return out;
}

function render(): string {
  const rows = collectDirs();
  const lines = [
    '# FILE-MAP',
    '',
    'Generated by `scripts/gen-file-map.ts` — **do not hand-edit.**',
    "Purpose comes from each directory's own TSDoc `@packageDocumentation`",
    'block, so it cannot drift from the code. Regenerate with',
    '`npx tsx scripts/gen-file-map.ts`; CI fails if this file is stale.',
    '',
    'A blank Purpose means that directory declares no `@packageDocumentation`',
    'block — an orientation gap, not an omission by the generator.',
    '',
    '| Directory | Source files | Purpose |',
    '| --- | ---: | --- |',
  ];
  for (const { dir, count, desc } of rows) {
    lines.push(`| \`${dir}\` | ${count} | ${desc} |`);
  }
  const totalFiles = rows.reduce((s, r) => s + r.count, 0);
  const undeclared = rows.filter((r) => !r.desc).length;
  lines.push(
    '',
    `${rows.length} source directories, ${totalFiles} files, ${undeclared} without a declared purpose.`,
    '',
  );
  return lines.join('\n');
}

function main(): number {
  const text = render();
  if (process.argv.includes('--check')) {
    const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf-8') : '';
    if (current !== text) {
      console.log(
        'FILE-MAP.md is stale - run: npx tsx scripts/gen-file-map.ts',
      );
      return 1;
    }
    console.log('FILE-MAP.md is current');
    return 0;
  }
  // Node's fs.writeFileSync writes the string's bytes as-is — no CRLF
  // translation — so the '\n'-joined text above lands as LF on every
  // platform, including Windows. That keeps FILE-MAP.md byte-identical
  // wherever it is generated and stops --check from tripping on line
  // endings alone (git's autocrlf checkout behavior is a separate, later
  // concern this script doesn't need to account for).
  fs.writeFileSync(OUT, text, { encoding: 'utf-8' });
  console.log(`wrote ${path.relative(ROOT, OUT)}`);
  return 0;
}

process.exit(main());
